### ISSUE TITLE
Attempt to wrap MatCreateComposite

### ISSUE THREAD

**Issue by chenwilliam77** [bmxam/PetscWrap.jl#4]
Hi there,

Thanks for all the work creating this cool wrapper! I've been trying to wrap `MatCreateComposite`, and my attempt is shown below. For the original function in PETSc, see https://www.mcs.anl.gov/petsc/petsc-current/docs/manualpages/Mat/MatCreateComposite.html#MatCreateComposite

```
function MatCreateComposite(comm::MPI.Comm, nmat::PetscInt, mats::Vector{PetscMat}, mat::PetscMat)   
    error = ccall((:MatCompositeAddMat, libpetsc), PetscErrorCode, (MPI.MPI_Comm, PetscInt, Ptr{CMat}, Ptr{CMat}),                  
                            comm, nmat, [x.ptr for x in mats], mat.ptr)    
    @assert iszero(error)
end
```

I've been getting segmentation faults when trying to use this function. In particular, I'm not sure that I'm handling the `const Mat *mats` argument correctly. I've never used C before, so I'm quite the novice to its syntax. I understand that the "*mats" means this input is passed by reference rather than value, so I should be passing in pointers. However, I'm not sure if `[x.ptr for x in mats]` is the right way to pass in the pointers for the vector of `Mat` types.

I've been trying to mirror the set up in https://www.mcs.anl.gov/petsc/petsc-current/src/mat/tutorials/ex9.c.html FYI.

Here is the example script I've been trying to use (based on your linear_system.jl)

```
using PetscWrap
PetscInitialize()

# Number of mesh points and mesh step
n = 11
Δx = 1. / (n - 1)

# Create a matrix and a vector
A = MatCreate() # place holder to which we write the final matrix
A1 = MatCreate() # component 1 of the composite matrix
A2 = MatCreate() # component 2 of the composite matrix
b = VecCreate()

# Set up
MatSetSizes(A1, PETSC_DECIDE, PETSC_DECIDE, n, n) # not absolutely sure this step is necessary
MatSetSizes(A2, PETSC_DECIDE, PETSC_DECIDE, n, n) # same for this step
VecSetSizes(b, PETSC_DECIDE, n)

# We can then use command-line options to set our matrix/vectors.
MatSetFromOptions(A1)  # not absolutely sure this step is necessary
MatSetFromOptions(A2) # same for this step
VecSetFromOptions(b)

# Finish the set up
MatSetUp(A1)  # not absolutely sure this step is necessary
MatSetUp(A2) # same for this step
VecSetUp(b)

# Build the b vector
b_start, b_end = VecGetOwnershipRange(b)

# Now let's build the right hand side vector. Their are various ways to do this, this is just one.
n_loc = VecGetLocalSize(b) # Note that n_loc = b_end - b_start...
VecSetValues(b, collect(b_start:b_end-1), 2 * ones(n_loc))

# And here is the differentiation matrix. Rembember that PETSc.MatSetValues simply ignores negatives rows indices.
A_start, A_end = MatGetOwnershipRange(A1) # A1 is going to hold one diagonal of the differentiation matrix
for i in A_start:A_end-1
    MatSetValues(A1, [i], [i-1], [-1.] / Δx, INSERT_VALUES) # MatSetValues(A, I, J, V, INSERT_VALUES)
end

A_start, A_end = MatGetOwnershipRange(A2) # A2 is going to hold another diagonal
for i in A_start:A_end-1
    MatSetValues(A2, [i], [i], [1.] / Δx, INSERT_VALUES) # MatSetValues(A, I, J, V, INSERT_VALUES)
end

# Set boundary condition (only the proc handling index `0` is acting)
(b_start == 0) && VecSetValue(b, 0, 0.)

# Assemble matrices
VecAssemblyBegin(b)
VecAssemblyEnd(b)
MatCreateComposite(2, [A1, A2], A) # segmentation fault occurs here, but I'm trying to do A = A1 + A2
```

**Comment by bmxam** [comment]
Hi,
I completely missed your issue notification. I'll take a look ASAP.

**Comment by bmxam** [comment]
Take a look at the branch 'composite' from the project. I have added a `create_composite_add(matrices)` function (in src/fancy/mat.jl). It creates a matrix from the sum of the elements of `matrices`. I've only checked the result on two 2×2 matrices.

I've also added the `MatMult` function.

However, I am not better than you with the C language : I've failed wrapping the `MatCreateComposite` directly, so I've implemented the "alternative version" proposed in the PETSc documentation.

Please tell me if this dev matches your need. Note that adding a version of the product of multiple matrices is very easy.

**Comment by bmxam** [comment]
I have merged the "composite" branch into master. A demo is available in `test/misc`. Don't hesitate to tell me if something's wrong or if you need anything else.

**Comment by chenwilliam77** [comment]
Thanks! I'll be taking a look soon and will let you know if anything is wrong. I'll reopen the issue if it doesn't seem to work.
